BigMartWeb/Areas/Admin/Controllers/CompanyController.cs
using BigMart.DataAccess.Repository.IRepository;
using BigMart.Models;
using BigMart.Models.ViewModels;
using BigMart.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;

namespace BigMartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork) { 
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();

            return View(objCompanyList);
        }

        public IActionResult Upsert(int? id)
        {
            //IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.Name,
            //    Value = u.Id.ToString()
            //});
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CategoryList"] = CategoryList;


            if(id == null || id == 0)
            {
                //create
                return View(new Company());
            } else
            {
                //update
                Company companyObj = _unitOfWork.Company.Get(u => u.Id == id);
                return View(companyObj);
            }

            
        }

        [HttpPost]
        public IActionResult Upsert(Company CompanyObj)
        {
            if (ModelState.IsValid)
            {
                 
                if(CompanyObj.Id == 0)
                {
                    _unitOfWork.Company.Add(CompanyObj);
                } else
                {
                    _unitOfWork.Company.Update(CompanyObj);
                }

                _unitOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(CompanyObj);
            }
        }


        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Company? CompanyFromDb = _unitOfWork.Company.Get(u => u.Id == id);

        //    if (CompanyFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(CompanyFromDb);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePost (int ? id)
        //{
        //    Company? obj = _unitOfWork.Company.Get(u => u.Id == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //      _unitOfWork.Company.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Category deleted succesfully!";

        //    return RedirectToAction("Index");
        //}
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new {data = objCompanyList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var CompanyToBeDeleted = _unitOfWork.Company.Get(u => u.Id == id);

            if (CompanyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.Company.Remove(CompanyToBeDeleted);
            _unitOfWork.Save();
            
            return Json(new { success = true, message = "Delete Succesfull! " });
        }
        #endregion
    }
}

BigMartWeb/Areas/Admin/Controllers/ProductController.cs
using BigMart.DataAccess.Repository.IRepository;
using BigMart.Models;
using BigMart.Models.ViewModels;
using BigMart.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;

namespace BigMartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment) { 
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        
        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return View(objProductList);
        }

        public IActionResult Upsert(int? id)
        {
            //IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.Name,
            //    Value = u.Id.ToString()
            //});
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CategoryList"] = CategoryList;

            ProductVM productVM = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };
            if(id == null || id == 0)
            {
                //create
                return View(productVM);
            } else
            {
                //update
                productVM.Product = _unitOfWork.Product.Get(u => u.Id == id);
                return View(productVM);
            }

            
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    if (!string.IsNullOrEmpty(productVM.Product.ImageUrl)) {
                        //delete old image
                        var oldImagePath = 
                            Path.Combine(wwwRootPath, productVM.Product.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productVM.Product.ImageUrl = @"\images\product\" + fileName;
                }

                if(productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                } else
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }

                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(productVM);
            }
        }


        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Product? productFromDb = _unitOfWork.Product.Get(u => u.Id == id);

        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(productFromDb);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePost (int ? id)
        //{
        //    Product? obj = _unitOfWork.Product.Get(u => u.Id == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //      _unitOfWork.Product.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Category deleted succesfully!";

        //    return RedirectToAction("Index");
        //}
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new {data = objProductList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id == id);

            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath =
                            Path.Combine(_webHostEnvironment.WebRootPath,
                            productToBeDeleted.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save();
            
            return Json(new { success = true, message = "Delete Succesfull! " });
        }
        #endregion
    }
}

BigMartWeb/Areas/Admin/Views/Company/Delete.cshtml
@model Product

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center ">
                <h2 class="text-white py-2">Delete Product</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3 mt-4">

                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" disabled class="form-control border-0 shadow" />
                    <label asp-for="Title" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" disabled class="form-control border-0 shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                </div>
                                <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" disabled class="form-control border-0 shadow" />
                    <label asp-for="ISBN" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" disabled class="form-control border-0 shadow" />
                    <label asp-for="Author" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" disabled class="form-control border-0 shadow" />
                    <label asp-for="ListPrice" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price50" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price50" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Price100" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price100" class="ms-2"></label>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-secondary border form-control">Back to List</a>
                    </div>
                </div>

            </div>


        </form>
    </div>

</div>

BigMartWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center ">
                <h2 class="text-white py-2">Company List</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">

        <div class="row pb-3">
            <div class="col-6">
                @*   <h2 class="text-primary">Category List</h2> *@
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Create a new Company
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <td>
                        Address
                    </td>
                    <th>
                        City
                    </th>
                    <th>
                       State
                    </th>
                    <th>
                        Phone Number
                    </th>
       
                    <th></th>
                </tr>
            </thead>
        </table>

    </div>


</div>


@section Scripts{
    <script src="~/js/company.js"></script>
}

BigMartWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center ">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Company</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
  
            <div class="row">
                <div class="col-12">
                    <div class="border p-3 mt-4">
                        @*   <div asp-validation-summary="All"></div> *@

                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>


                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" class="form-control border-0 shadow" />
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
  
                        <div class="row mt-3">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>

                                }

                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" asp-action="Index" class="btn btn-secondary border form-control">Back to List</a>
                            </div>
                        </div>

                    </div>
                </div>
                
            </div>

        </form>
    </div>

</div>


@section Scripts {
    <script>
        tinymce.init({
          selector: 'textarea',
          plugins: [
            // Core editing features
            'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'lists', 'table', 'visualblocks', 'wordcount',
            // Your account includes a free trial of TinyMCE premium features
          ],
          toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent',
          tinycomments_mode: 'embedded',
          tinycomments_author: 'Author name',
          mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
          ],
          ai_request: (request, respondWith) => respondWith.string(() => Promise.reject('See docs to implement AI Assistant')),
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}